export const Text = {
    CLOSE:"Close",
        CREATE_CHANNEL: "Create Channel",
        CREATE_CHANNEL_DESCRIPTION: "Public or private space for your projects",
        CHANNEL_NAME_LABEL: "Channel Name",
        CHANNEL_NAME_PLACEHOLDER: "e.g. project-apollo",
        ADD_MEMBERS_LABEL: "Add Members",
        SEARCH_PLACEHOLDER: "Search for members to add...",
        NO_RESULTS: "No results",
        NO_MEMBERS: "No members",
        MEMBER_COUNT: (count: number) => `${count} member${count !== 1 ? 's' : ''}`,
        CREATE_CHANNEL_BUTTON: "Create Channel",
        CREATING: "Creating...",
        CHANNEL_ALREADY_EXISTS: (name: string) => `Channel #${name} already exists`,
        CHANNEL_NAME_REQUIRED: "Channel name is required",
        AT_LEAST_ONE_MEMBER: "At least one member is required",
        CHANNEL_CREATED: "Channel created successfully!",
        ERROR_CREATING_CHANNEL: "Error creating channel",
        LOADING_WORKSPACE: "Loading workspace...",
        WORKSPACE_NAME: (name: string) => `Workspace: ${name}`,
        SEARCHING: "Searching...",
}